spring:
  datasource  :
    drivername: org.postgresql.Driver
    url       : jdbc:postgresql://localhost:5432/cyber_bullying
    username  : postgres
    password  : password

  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

server:
  port : 8181